export const STOCK_CONSTANTS = {
  title: 'Stock Dashboard',
  searchPlaceholder: 'Enter stock symbol (e.g., TCS, INFY, RELIANCE)',
  currency: {
    code: 'INR',
    symbol: '₹',
    locale: 'en-IN',
  },
  realtime: {
    refreshMs: 30_000, // 30s polling for demo; tune as needed
  },
  rates: {
    gold: 'Gold Rate',
    silver: 'Silver Rate',
    unit: 'per gram',
    loading: 'Loading rates...',
    error: 'Unable to load rates',
  },
  chart: {
    defaultPeriod: '1D',
    periods: ['1D', '1W', '1M', '3M', '1Y', '5Y'] as const,
    loading: 'Loading chart data...',
    error: 'Unable to load chart data',
    noData: 'No data available for this symbol',
    dataPoints: {
      '1D': 24,
      '1W': 7,
      '1M': 30,
      '3M': 90,
      '1Y': 365,
      '5Y': 1825,
    } as const,
  },
  messages: {
    searchRequired: 'Please enter a stock symbol',
    invalidSymbol: 'Invalid stock symbol',
    apiError: 'Service temporarily unavailable',
  },
  api: {
    usdToInrFallback: 83,
    ouncesToGrams: 31.1034768,
    mockPriceRange: {
      min: 2500,
      max: 4500,
      variance: 20,
    },
    mockVolumeRange: {
      min: 100000,
      max: 1100000,
    },
    mockVariance: 10,
    mockPriceSpread: 5,
    mockMetalRates: {
      gold: {
        base: 6200,
        variance: 50,
      },
      silver: {
        base: 75,
        variance: 2,
      },
    },
  },
  errors: {
    parseMetalRates: 'Unable to parse metal rates',
    loadMetalRates: 'Unable to load metal rates',
    parseStockData: 'Unable to parse stock data',
    loadStockData: 'Unable to load stock data',
    invalidResponse: 'Invalid API response',
    invalidSeries: 'Invalid data series',
    invalidPoint: 'Invalid data point',
    invalidNumbers: 'Invalid numeric values',
    invalidQuote: 'Invalid quote data',
    invalidPrice: 'Invalid price data',
    invalidChartSeries: 'Invalid chart series',
    invalidChartResult: 'Invalid chart result',
    invalidIndicators: 'Invalid indicators',
    invalidQuoteArray: 'Invalid quote array',
  },
  companies: {
    AAPL: 'Apple Inc.',
    GOOGL: 'Alphabet Inc.',
    MSFT: 'Microsoft Corporation',
    AMZN: 'Amazon.com Inc.',
    TSLA: 'Tesla Inc.',
    META: 'Meta Platforms Inc.',
    NVDA: 'NVIDIA Corporation',
    NFLX: 'Netflix Inc.',
    RELIANCE: 'Reliance Industries',
    TCS: 'Tata Consultancy Services',
    INFY: 'Infosys Limited',
    HDFCBANK: 'HDFC Bank',
    ITC: 'ITC Limited',
  } as const,
  symbolMappings: {
    global: {
      RELIANCE: 'RELIANCE.BSE',
      TCS: 'TCS.BSE',
      INFY: 'INFY.BSE',
      HDFCBANK: 'HDFCBANK.BSE',
      ITC: 'ITC.BSE',
    } as const,
    yahoo: {
      RELIANCE: 'RELIANCE.NS',
      TCS: 'TCS.NS',
      INFY: 'INFY.NS',
      HDFCBANK: 'HDFCBANK.NS',
      ITC: 'ITC.NS',
      AAPL: 'AAPL',
      MSFT: 'MSFT',
      GOOGL: 'GOOGL',
    } as const,
  },
  chartMappings: {
    '1D': { yfPeriod: '1d', yfInterval: '30m' },
    '1W': { yfPeriod: '5d', yfInterval: '1d' },
    '1M': { yfPeriod: '1mo', yfInterval: '1d' },
    '3M': { yfPeriod: '3mo', yfInterval: '1d' },
    '1Y': { yfPeriod: '1y', yfInterval: '1wk' },
    '5Y': { yfPeriod: '5y', yfInterval: '1mo' },
  } as const,
} as const;
